BlogApp/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    path('', include(('apps.home.urls','blog'),namespace='blog')),
    path('', include(('apps.post.urls','post'),namespace='post')),
]

apps/home/urls.py
from django.urls import path

from .views import HomeView

urlpatterns = [
    path('', HomeView.as_view(), name='index'),
]

apps/post/urls.py
from django.urls import path

from .views import PostList, DetailPost

urlpatterns = [
    path('posts/', PostList.as_view(), name='posts'),
	path('post/detalle/<int:pk>/', DetailPost.as_view(),name='detail_post'),    
]

apps/author/models.py
from __future__ import unicode_literals

from django.db import models

class Author(models.Model):

    name = models.CharField(
        max_length = 255,
        help_text = "Nombre"
    )

    '''
    image = models.ImageField(
        upload_to = "images/author",
        blank=True, 
        null=True
    )
    '''

    description = models.TextField(
        help_text = "Descripcion"
    )

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name = 'Autor'
        verbose_name_plural = 'Autores'

apps/home/models.py
from django.db import models

# Create your models here.

apps/post/models.py
from __future__ import unicode_literals

from django.db import models
from apps.author.models import Author

class Post(models.Model):

    title = models.CharField(
        max_length = 255,
        help_text = "Titulo"
    )

    autor = models.ForeignKey(
        Author,
        on_delete=models.CASCADE,
        help_text = "Autor"
    )

    '''
    image = models.ImageField(
        upload_to = "images/post",
        help_text = "imagen"
    )
    '''

    content = models.TextField(
        help_text = "Contenido"
    )

    publication_date = models.DateTimeField(
        help_text = "Fecha"
    )

    status = models.BooleanField(
        help_text = "Estado",
        default = True
    )

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']
        verbose_name = "Post"
        verbose_name_plural = "Posts"

apps/author/views.py
from django.shortcuts import render

# Create your views here.

apps/home/views.py
from django.shortcuts import render
from django.utils import timezone
from django.views.generic import TemplateView
from apps.post.models import Post

class HomeView(TemplateView):

    template_name = "index.html"
    context_object_name = "posts"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        print("CONTEXT >> ", context)
        return context    

apps/post/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic import TemplateView, ListView, DetailView, UpdateView, CreateView, DeleteView

from .models import Post

class PostList(ListView):
	model = Post
	template_name = "blog.html"
	context_object_name = 'posts'
    
class DetailPost(DetailView):
	model = Post
	template_name = 'read.html'
	context_object_name = 'post'

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %} <title></title>{% endblock title %}

    {% block description %}
        <meta name="description" content="Project Django">
        <meta name="keywords" content="Tags Django, Python, Postgres, Ajax , Jquery">
    {% endblock description %}    

    
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styles-merged.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    {% block extracss %}
        <!-- Block extracss -->
    {% endblock extracss %}

</head>

<body>

    <header role="banner" class="probootstrap-header">
        {% include 'partials/header.html' %}
    </header>

    {% block content %}
        <!-- Block Content -->
    {% endblock content %}

    <footer role="contentinfo" class="probootstrap-footer">
        {% include 'partials/footer.html' %}
    </footer>

    <script src="{% static 'js/scripts.min.js' %}"></script>
    <script src="{% static 'js/main.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>

    {% block extrajs %}
    <!-- extrajs -->
    {% endblock extrajs %}
</body>

</html>

templates/blog.html
{% extends 'base.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> {% block title %}
    <title>DjBlog</title> {% endblock title %} {% block description %}
    <meta name="description" content="Project Django">
    <meta name="keywords" content="Tags Django, Python, Postgres, Ajax , Jquery"> {% endblock description %}

</head>

<body>


    {% block content %}
    <section class="probootstrap-section">
        <div class="container">

            <div class="row">

                {% for post in posts %}
                <div class="col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
                    <div class="probootstrap-block-image">
                        <figure>
                            <img src="{% static 'img/djangolove.png' %}" alt="Free Bootstrap Template by uicookies.com">
                        </figure>
                        <div class="text">
                            <span class="date">{{ post.publication_date }}</span>
                            <h3>
                                <a href="{% url 'post:detail_post' post.id %}">{{ post.title }}</a>
                            </h3>
                            <p>{{ post.autor }}</p>
                            <p>
                                <a href="{% url 'post:detail_post' post.id %}" class="link-with-icon">leer mas 
                                    <i class=" icon-chevron-right"></i>
                                </a>
                            </p>
                        </div>
                    </div>
                </div>  
                {% empty %}          
                    <h2>Sin registros Existentes</h2>                    
                {% endfor %}
                
            </div>

            <div class="row mb50">
                <div class="col-md-12 section-heading text-center">
                    <h2> Dejanos un comentario </h2>
                </div>
            </div>
            <div class="row">
                <div id="disqus_thread"></div>
                <script>

                    (function () {
                        var d = document, s = d.createElement('script');
                        s.src = 'https://devzone-2.disqus.com/embed.js';
                        s.setAttribute('data-timestamp', +new Date());
                        (d.head || d.body).appendChild(s);
                    })();
                </script>
                <noscript>Please enable JavaScript to view the
                    <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a>
                </noscript>
            </div>
        </div>
    </section>
    {% endblock content %}

</body>

</html>

templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% block title %}<title>DjBlog</title> {% endblock title %}

     {% block description %}
      <meta name="description" content="Project Django">
      <meta name="keywords" content="Tags Django, Python, Postgres, Ajax , Jquery"> 
    {% endblock description %}

  </head>
  <body>
    
    {% block content %}

    <section class="probootstrap-section probootstrap-feature-first">
      <div class="container">
        <div class="row mb70" style="margin-top: -120px;">
          <div class="col-md-4 probootstrap-animate">
            <div class="probootstrap-box">
              <div class="icon">
                <i class="icon-presentation"></i>
              </div>
              <h3>Business presentation</h3>
              <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic
                country, in which roasted parts of sentences fly into your mouth.</p>
            </div>
          </div>
          <div class="col-md-4 probootstrap-animate">
            <div class="probootstrap-box">
              <div class="icon">
                <i class="icon-bargraph"></i>
              </div>
              <h3>Business growth</h3>
              <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic
                country, in which roasted parts of sentences fly into your mouth.</p>
            </div>
          </div>
          <div class="col-md-4 probootstrap-animate">
            <div class="probootstrap-box">
              <div class="icon">
                <i class="icon-megaphone2"></i>
              </div>
              <h3>Standout from the crowd</h3>
              <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic
                country, in which roasted parts of sentences fly into your mouth.</p>
            </div>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 col-md-offset-4 probootstrap-animate">
            <p class="text-center">
              <a href="#" class="btn btn-primary btn-lg btn-block" role="button">{{ now }}</a>
            </p>
          </div>
        </div>
      </div>
    </section>
    
    <section class="probootstrap-section probootstrap-section-extra">
      <div class="container-fluid probootstrap-absolute">
        <div class="row">
          <div class="col-md-7 col-md-push-6 probootstrap-animate" data-animate-effect="fadeInRight">
            <img src="{% static 'img/img_showcase_2.jpg' %}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive shadow-left">
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-5 col-md-5 section-heading probootstrap-animate">
            <h2>We guide companies</h2>
            <p class="lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.
              Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
            </p>
    
            <blockquote class="probootstrap-quote">
              <figure class="probootstrap-quote-logo uber">
                <img src="{% static 'img/uber.png' %}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive">
              </figure>
              <p>&ldquo;A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic
                country, in which roasted parts of sentences fly into your mouth.&rdquo;</p>
              <p class="probootstrap-quote-author">
                <img src="{% static 'img/person_1.jpg' %}" alt="Free Bootstrap Template by uicookies.com"> Chris Worth, Uber</p>
            </blockquote>
          </div>
        </div>
      </div>
    </section>
    
    <section class="probootstrap-section probootstrap-section-extra">
      <div class="container-fluid probootstrap-absolute">
        <div class="row">
          <div class="col-md-8 col-md-pull-2 probootstrap-animate" data-animate-effect="fadeInLeft">
            <img src="{% static 'img/laptop_1.jpg' %}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive">
          </div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-5 col-md-5 col-md-push-6 section-heading probootstrap-animate">
            <h2>We design extraordinary</h2>
            <p class="lead">Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.
              Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
            </p>
            <blockquote class="probootstrap-quote">
              <figure class="probootstrap-quote-logo facebook">
                <img src="{% static 'img/facebook.png' %}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive">
              </figure>
              <p>&ldquo;A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic
                country, in which roasted parts of sentences fly into your mouth.&rdquo;</p>
              <p class="probootstrap-quote-author">
                <img src="{% static 'img/person_5.jpg' %}" alt="Free Bootstrap Template by uicookies.com"> Janet Morris, Facebook</p>
            </blockquote>
          </div>
        </div>
      </div>
    </section>
    
    <section class="probootstrap-section probootstrap-section-colored">
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-md-offset-2 section-heading mb50 text-center probootstrap-animate">
            <h2>More Benefits</h2>
            <p class="lead">A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic
              country, in which roasted parts of sentences fly into your mouth.</p>
          </div>
        </div>
        <div class="row">
          <div class="col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
            <h3 class="heading-with-icon">
              <i class="icon-heart2"></i>
              <span>We bring emotion</span>
            </h3>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.
              Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
            </p>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
            <h3 class="heading-with-icon">
              <i class="icon-rocket"></i>
              <span>We guide companies</span>
            </h3>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.
              Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
            </p>
          </div>
          <div class="clearfix visible-sm-block"></div>
          <div class="col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
            <h3 class="heading-with-icon">
              <i class="icon-image"></i>
              <span>We design extraordinary</span>
            </h3>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.
              Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
            </p>
          </div>
          <div class="clearfix visible-md-block"></div>
          <div class="col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
            <h3 class="heading-with-icon">
              <i class="icon-briefcase"></i>
              <span>We bring emotion</span>
            </h3>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.
              Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
            </p>
          </div>
          <div class="clearfix visible-sm-block"></div>
          <div class="col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
            <h3 class="heading-with-icon">
              <i class="icon-chat"></i>
              <span>We guide companies</span>
            </h3>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.
              Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
            </p>
          </div>
          <div class="col-md-4 col-sm-6 col-xs-12 probootstrap-animate">
            <h3 class="heading-with-icon">
              <i class="icon-colours"></i>
              <span>We design extraordinary</span>
            </h3>
            <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.
              Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.
            </p>
          </div>
          <div class="clearfix visible-sm-block"></div>
        </div>
      </div>
    </section>
    {% endblock content %}
  </body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>uiCookies:Sublime &mdash; Free Bootstrap Theme, Free Responsive Bootstrap Website Template</title>
    <meta name="description" content="Free Bootstrap Theme by uicookies.com">
    <meta name="keywords" content="free website templates, free bootstrap themes, free template, free bootstrap, free website template">
    
    <link href="https://fonts.googleapis.com/css?family=Rubik:300,400,500" rel="stylesheet"> 
    <link rel="stylesheet" href="css/styles-merged.css">
    <link rel="stylesheet" href="css/style.min.css">
    <link rel="stylesheet" href="css/custom.css">

    <!--[if lt IE 9]>
      <script src="js/vendor/html5shiv.min.js"></script>
      <script src="js/vendor/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    


  <!-- START: header -->
  <header role="banner" class="probootstrap-header probootstrap-header-no-intro">
    <div class="container-fluid">
      <!-- <div class="row"> -->
        <a href="index.html" class="probootstrap-logo">Sublime<span>.</span></a>
        
        <a href="#" class="probootstrap-burger-menu visible-xs" ><i>Menu</i></a>
        <div class="mobile-menu-overlay"></div>

        <nav role="navigation" class="probootstrap-nav hidden-xs">
          <ul class="probootstrap-main-nav">
            <li><a href="index.html">Home</a></li>
            <li><a href="blog.html">Blog</a></li>
            <li><a href="pricing.html">Pricing</a></li>
            <li><a href="tour.html">Tour</a></li>
            <li><a href="login.html">Log in</a></li>
            <li class="probootstrap-cta"><a href="signup.html">Sign up</a></li>
          </ul>
          <div class="extra-text visible-xs">
            <a href="#" class="probootstrap-burger-menu"><i>Menu</i></a>
            <h5>Social</h5>
            <ul class="social-buttons">
              <li><a href="#"><i class="icon-twitter"></i></a></li>
              <li><a href="#"><i class="icon-facebook"></i></a></li>
              <li><a href="#"><i class="icon-instagram2"></i></a></li>
            </ul>
            <p><small>&copy; Copyright 2017. All Rights Reserved.</small></p>
          </div>
        </nav>

      <!-- </div> -->
    </div>
    
  
  </header>
  <!-- END: header -->
  
  <section class="probootstrap-section">
    <div class="container">
      <div class="row">
        <div class="col-md-12 text-center section-heading">
          <h2>Log in</h2>
        </div>
      </div>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <form method="post" class="probootstrap-form probootstrap-form-box">
            <div class="form-group">
              <label for="username">Username</label>
              <input type="username" name="username" id="username" class="form-control">
            </div>
            <div class="form-group">
              <label for="username">Password</label>
              <input type="password" name="password" id="password" class="form-control">
            </div>
            <div class="form-group mb50">
              <input type="submit" value="Log in" class="btn btn-primary btn-block">
            </div>
            <div class="form-group text-center">
              <p class="form-note-link"><small><a href="signup.html">Don't have an account? Sign Up for free</a></small> <br> <small><a href="#">Forgot password?</a></small></p>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>
  
  
  <!-- START: footer -->
  <footer role="contentinfo" class="probootstrap-footer">
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <div class="probootstrap-footer-widget">
            <h3>About</h3>
            <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
            <p><a href="#" class="link-with-icon">Learn More <i class=" icon-chevron-right"></i></a></p>
          </div>
        </div>
        <div class="col-md-4">
          <div class="probootstrap-footer-widget">
            <h3>Blog</h3>
            <ul class="probootstrap-blog-list">
              <li>
                <a href="#">
                  <figure><img src="img/img_2.jpg" alt="Free Bootstrap Template by uicookies.com" class="img-responsive"></figure>
                  <div class="text">
                    <h4>River named Duden flows</h4>
                    <p>A small river named Duden flows by their place</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="#">
                  <figure><img src="img/img_3.jpg" alt="Free Bootstrap Template by uicookies.com" class="img-responsive"></figure>
                  <div class="text">
                    <h4>River named Duden flows</h4>
                    <p>A small river named Duden flows by their place</p>
                  </div>
                </a>
              </li>
              <li>
                <a href="#">
                  <figure><img src="img/img_2.jpg" alt="Free Bootstrap Template by uicookies.com" class="img-responsive"></figure>
                  <div class="text">
                    <h4>River named Duden flows</h4>
                    <p>A small river named Duden flows by their place</p>
                  </div>
                </a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-md-4">
          <div class="probootstrap-footer-widget">
            <h3>Contact</h3>
            <ul class="probootstrap-contact-info">
              <li><i class="icon-location2"></i> <span>198 West 21th Street, Suite 721 New York NY 10016</span></li>
              <li><i class="icon-mail"></i><span>info@domain.com</span></li>
              <li><i class="icon-phone2"></i><span>+123 456 7890</span></li>
            </ul>
            
          </div>
        </div>
      </div>
      <div class="row mt40">
        <div class="col-md-12 text-center">
          <ul class="probootstrap-footer-social">
            <li><a href=""><i class="icon-twitter"></i></a></li>
            <li><a href=""><i class="icon-facebook"></i></a></li>
            <li><a href=""><i class="icon-instagram2"></i></a></li>
          </ul>
          <p>
            <small>&copy; 2017 <a href="https://uicookies.com/" target="_blank">uiCookies:Sublime</a>. All Rights Reserved. <br> Designed &amp; Developed by <a href="https://uicookies.com/" target="_blank">uicookies.com</a> Demo Images: Unsplash</small>
          </p>
          
        </div>
      </div>
    </div>
  </footer>
  <!-- END: footer -->



  <script src="js/scripts.min.js"></script>
  <script src="js/main.min.js"></script>
  <script src="js/custom.js"></script>

  </body>
</html>

templates/partials/footer.html
{% load staticfiles %}

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="probootstrap-footer-widget">
                <h3>About</h3>
                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic
                    country, in which roasted parts of sentences fly into your mouth.</p>
                <p>
                    <a href="#" class="link-with-icon">Learn More
                        <i class=" icon-chevron-right"></i>
                    </a>
                </p>
            </div>
        </div>
        <div class="col-md-4">
            <div class="probootstrap-footer-widget">
                <h3>Blog</h3>
                <ul class="probootstrap-blog-list">
                    <li>
                        <a href="#">
                            <figure>
                                <img src="{% static 'img/img_2.jpg' %}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive">
                            </figure>
                            <div class="text">
                                <h4>River named Duden flows</h4>
                                <p>A small river named Duden flows by their place</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <figure>
                                <img src="{% static 'img/img_3.jpg' %}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive">
                            </figure>
                            <div class="text">
                                <h4>River named Duden flows</h4>
                                <p>A small river named Duden flows by their place</p>
                            </div>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <figure>
                                <img src="{% static 'img/img_2.jpg' %}" alt="Free Bootstrap Template by uicookies.com" class="img-responsive">
                            </figure>
                            <div class="text">
                                <h4>River named Duden flows</h4>
                                <p>A small river named Duden flows by their place</p>
                            </div>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="col-md-4">
            <div class="probootstrap-footer-widget">
                <h3>Contact</h3>
                <ul class="probootstrap-contact-info">
                    <li>
                        <i class="icon-location2"></i>
                        <span>198 West 21th Street, Suite 721 New York NY 10016</span>
                    </li>
                    <li>
                        <i class="icon-mail"></i>
                        <span>info@domain.com</span>
                    </li>
                    <li>
                        <i class="icon-phone2"></i>
                        <span>+123 456 7890</span>
                    </li>
                </ul>

            </div>
        </div>
    </div>
    <div class="row mt40">
        <div class="col-md-12 text-center">
            <ul class="probootstrap-footer-social">
                <li>
                    <a href="">
                        <i class="icon-twitter"></i>
                    </a>
                </li>
                <li>
                    <a href="">
                        <i class="icon-facebook"></i>
                    </a>
                </li>
                <li>
                    <a href="">
                        <i class="icon-instagram2"></i>
                    </a>
                </li>
            </ul>
            <p>
                <small>&copy; 2017
                    <a href="https://uicookies.com/" target="_blank">uiCookies:Sublime</a>. All Rights Reserved.
                    <br> Designed &amp; Developed by
                    <a href="https://uicookies.com/" target="_blank">uicookies.com</a> Demo Images: Unsplash</small>
            </p>

        </div>
    </div>
</div>

templates/partials/header.html
<div class="container-fluid">

    <a href="index.html" class="probootstrap-logo">DjBlog
        <span>.</span>
    </a>

    <a href="#" class="probootstrap-burger-menu visible-xs">
        <i>Menu</i>
    </a>
    <div class="mobile-menu-overlay"></div>

    <nav role="navigation" class="probootstrap-nav hidden-xs">
        <ul class="probootstrap-main-nav">
            <li>
                <a href="index.html">Home</a>
            </li>
            <li>
                <a href="blog.html">Blog</a>
            </li>
            <li>
                <a href="pricing.html">Pricing</a>
            </li>
            <li>
                <a href="tour.html">Tour</a>
            </li>
            <li>
                <a href="login.html">Log in</a>
            </li>
            <li class="probootstrap-cta">
                <a href="signup.html">Sign up</a>
            </li>
        </ul>
        <div class="extra-text visible-xs">
            <a href="#" class="probootstrap-burger-menu">
                <i>Menu</i>
            </a>
            <h5>Social</h5>
            <ul class="social-buttons">
                <li>
                    <a href="#">
                        <i class="icon-twitter"></i>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="icon-facebook"></i>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="icon-instagram2"></i>
                    </a>
                </li>
            </ul>
        </div>
    </nav>

    <section class="probootstrap-intro">
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2">
                    <h1 class="probootstrap-animate">DjBlog Post Sobre Tecnologia</h1>
                    <div class="probootstrap-subtitle probootstrap-animate">
                        <h2>Tienes que aprender a aprovechar la tecnología para poder usarla para cosas positivas sin estar desconectado de la naturaleza.</h2>
                    </div>
                    <p class="watch-intro probootstrap-animate">
                        <a href="#">.-Talib Kweli.</a>
                    </p>
                </div>
            </div>
        </div>
    </section>

</div>